### ISSUE TITLE
Unable to install databricks adapter through packages and dbt deps

### ISSUE THREAD

**Issue by ivankpenev** [databricks/dbt-databricks#205]
### Describe the bug
We are trying to setup the dbt-adapter in our dbt environment. We've been running the spark-adapter beforehand. We install packages using dbt deps and specifying packages. When we add the dbt-databricks adapter to the packages list we get the following error:

```
source % dbt --debug  deps --project-dir=/Users/ipenev/repos/repo3/source/data_ops/dbt --profiles-dir=/Users/ipenev/repos/repo3/source/data_ops/dbt --target=dev
2022-10-06 17:23:16.939813 (MainThread): Running with dbt=0.20.2
2022-10-06 17:23:16.997800 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.deps.DepsTask'>, debug=True, defer=None, log_cache_events=False, log_format='default', partial_parse=None, profile=None, profiles_dir='/Users/ipenev/repos/repo3/source/data_ops/dbt', project_dir='/Users/ipenev/repos/repo3/source/data_ops/dbt', record_timing_info=None, rpc_method='deps', single_threaded=False, state=None, strict=False, target='dev', test_new_parser=False, use_cache=True, use_colors=None, use_experimental_parser=False, vars='{}', warn_error=False, which='deps', write_json=True)
2022-10-06 17:23:16.998395 (MainThread): Tracking: tracking
2022-10-06 17:23:17.011898 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12505a910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1261f23d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1261f20a0>]}
2022-10-06 17:23:17.013316 (MainThread): Set downloads directory='/var/folders/g7/6hvwgqks4kl69bpl428pdl5h0000gn/T/dbt-downloads-cvlom8wt'
2022-10-06 17:23:17.013788 (MainThread): Making package registry request: GET https://hub.getdbt.com/api/v1/index.json
2022-10-06 17:23:17.098672 (MainThread): Response from registry: GET https://hub.getdbt.com/api/v1/index.json 200
2022-10-06 17:23:17.098890 (MainThread): Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json
2022-10-06 17:23:17.180818 (MainThread): Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils.json 200
2022-10-06 17:23:17.184042 (MainThread): Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils/0.7.6.json
2022-10-06 17:23:17.280394 (MainThread): Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/dbt_utils/0.7.6.json 200
2022-10-06 17:23:17.280695 (MainThread): Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/spark_utils.json
2022-10-06 17:23:17.376761 (MainThread): Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/spark_utils.json 200
2022-10-06 17:23:17.378420 (MainThread): Making package registry request: GET https://hub.getdbt.com/api/v1/dbt-labs/spark_utils/0.2.4.json
2022-10-06 17:23:17.476903 (MainThread): Response from registry: GET https://hub.getdbt.com/api/v1/dbt-labs/spark_utils/0.2.4.json 200
2022-10-06 17:23:17.477542 (MainThread): Executing "git clone --depth 1 https://github.com/databricks/dbt-databricks.git c4cd59c6b0d9803e4aa7bb7d61ccf434"
2022-10-06 17:23:18.531971 (MainThread): STDOUT: "b''"
2022-10-06 17:23:18.532513 (MainThread): STDERR: "b"Cloning into 'c4cd59c6b0d9803e4aa7bb7d61ccf434'...\n""
2022-10-06 17:23:18.533404 (MainThread): Pulling new dependency c4cd59c6b0d9803e4aa7bb7d61ccf434.
2022-10-06 17:23:18.533499 (MainThread): Executing "git rev-parse HEAD"
2022-10-06 17:23:18.547641 (MainThread): STDOUT: "b'e92175426dfcef8f536822e1b8b5e626bcee30c3\n'"
2022-10-06 17:23:18.548122 (MainThread): STDERR: "b''"
2022-10-06 17:23:18.548275 (MainThread):   Checking out revision HEAD.
2022-10-06 17:23:18.548353 (MainThread): Executing "git remote set-branches origin HEAD"
2022-10-06 17:23:18.556476 (MainThread): STDOUT: "b''"
2022-10-06 17:23:18.556807 (MainThread): STDERR: "b''"
2022-10-06 17:23:18.556917 (MainThread): Executing "git fetch origin --depth 1 --tags HEAD"
2022-10-06 17:23:19.652205 (MainThread): STDOUT: "b''"
2022-10-06 17:23:19.652629 (MainThread): STDERR: "b'From https://github.com/databricks/dbt-databricks\n * branch            HEAD       -> FETCH_HEAD\n * [new tag]         v0.13.0    -> v0.13.0\n * [new tag]         v0.14.3    -> v0.14.3\n * [new tag]         v0.15.3    -> v0.15.3\n * [new tag]         v0.16.0    -> v0.16.0\n * [new tag]         v0.16.1    -> v0.16.1\n * [new tag]         v0.17.0    -> v0.17.0\n * [new tag]         v0.17.1    -> v0.17.1\n * [new tag]         v0.17.2    -> v0.17.2\n * [new tag]         v0.18.0    -> v0.18.0\n * [new tag]         v0.18.1    -> v0.18.1\n * [new tag]         v0.18.1.1  -> v0.18.1.1\n * [new tag]         v0.18.2    -> v0.18.2\n * [new tag]         v0.19.0    -> v0.19.0\n * [new tag]         v0.19.0.1  -> v0.19.0.1\n * [new tag]         v0.19.0rc1 -> v0.19.0rc1\n * [new tag]         v0.19.1    -> v0.19.1\n * [new tag]         v0.19.1b2  -> v0.19.1b2\n * [new tag]         v0.19.1rc1 -> v0.19.1rc1\n * [new tag]         v0.19.2    -> v0.19.2\n * [new tag]         v0.19.2rc2 -> v0.19.2rc2\n * [new tag]         v0.20.0    -> v0.20.0\n * [new tag]         v0.20.0rc1 -> v0.20.0rc1\n * [new tag]         v0.20.0rc2 -> v0.20.0rc2\n * [new tag]         v0.20.1    -> v0.20.1\n * [new tag]         v0.20.1rc1 -> v0.20.1rc1\n * [new tag]         v0.20.2    -> v0.20.2\n * [new tag]         v0.20.2rc1 -> v0.20.2rc1\n * [new tag]         v0.20.2rc2 -> v0.20.2rc2\n * [new tag]         v0.21.0    -> v0.21.0\n * [new tag]         v0.21.0b1  -> v0.21.0b1\n * [new tag]         v0.21.0b2  -> v0.21.0b2\n * [new tag]         v0.21.0rc1 -> v0.21.0rc1\n * [new tag]         v0.21.0rc2 -> v0.21.0rc2\n * [new tag]         v0.21.1    -> v0.21.1\n * [new tag]         v1.0.0     -> v1.0.0\n * [new tag]         v1.0.1     -> v1.0.1\n * [new tag]         v1.0.2     -> v1.0.2\n * [new tag]         v1.0.3     -> v1.0.3\n * [new tag]         v1.1.0     -> v1.1.0\n * [new tag]         v1.1.1     -> v1.1.1\n * [new tag]         v1.1.2     -> v1.1.2\n * [new tag]         v1.1.3     -> v1.1.3\n * [new tag]         v1.1.4     -> v1.1.4\n * [new tag]         v1.1.5     -> v1.1.5\n * [new tag]         v1.2.0     -> v1.2.0\n * [new tag]         v1.2.1     -> v1.2.1\n * [new tag]         v1.2.2     -> v1.2.2\n * [new tag]         v1.2.3     -> v1.2.3\n'"
2022-10-06 17:23:19.652863 (MainThread): Executing "git tag --list"
2022-10-06 17:23:19.661725 (MainThread): STDOUT: "b'v0.13.0\nv0.14.3\nv0.15.3\nv0.16.0\nv0.16.1\nv0.17.0\nv0.17.1\nv0.17.2\nv0.18.0\nv0.18.1\nv0.18.1.1\nv0.18.2\nv0.19.0\nv0.19.0.1\nv0.19.0rc1\nv0.19.1\nv0.19.1b2\nv0.19.1rc1\nv0.19.2\nv0.19.2rc2\nv0.20.0\nv0.20.0rc1\nv0.20.0rc2\nv0.20.1\nv0.20.1rc1\nv0.20.2\nv0.20.2rc1\nv0.20.2rc2\nv0.21.0\nv0.21.0b1\nv0.21.0b2\nv0.21.0rc1\nv0.21.0rc2\nv0.21.1\nv1.0.0\nv1.0.1\nv1.0.2\nv1.0.3\nv1.1.0\nv1.1.1\nv1.1.2\nv1.1.3\nv1.1.4\nv1.1.5\nv1.2.0\nv1.2.1\nv1.2.2\nv1.2.3\n'"
2022-10-06 17:23:19.662133 (MainThread): STDERR: "b''"
2022-10-06 17:23:19.662268 (MainThread): Executing "git reset --hard origin/HEAD"
2022-10-06 17:23:19.679297 (MainThread): STDOUT: "b'HEAD is now at e921754 Add a test for "consolidate timestamp macros". (#200)\n'"
2022-10-06 17:23:19.679689 (MainThread): STDERR: "b''"
2022-10-06 17:23:19.679794 (MainThread): Executing "git rev-parse HEAD"
2022-10-06 17:23:19.686468 (MainThread): STDOUT: "b'e92175426dfcef8f536822e1b8b5e626bcee30c3\n'"
2022-10-06 17:23:19.686774 (MainThread): STDERR: "b''"
2022-10-06 17:23:19.686863 (MainThread):   Checked out at e921754.
2022-10-06 17:23:19.686990 (MainThread): WARNING: The git package "https://github.com/databricks/dbt-databricks.git" 
	is not pinned, using HEAD (default branch).
	This can introduce breaking changes into your project without warning!

See https://docs.getdbt.com/docs/package-management#section-specifying-package-versions
2022-10-06 17:23:19.687561 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12505ac70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x126026fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1261f22b0>]}
2022-10-06 17:23:19.688023 (MainThread): Flushing usage events
2022-10-06 17:23:20.129044 (MainThread): Encountered an error:
2022-10-06 17:23:20.129536 (MainThread): Runtime Error
  no dbt_project.yml found at expected path /var/folders/g7/6hvwgqks4kl69bpl428pdl5h0000gn/T/dbt-downloads-cvlom8wt/c4cd59c6b0d9803e4aa7bb7d61ccf434/dbt_project.yml
2022-10-06 17:23:20.134408 (MainThread): Traceback (most recent call last):
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/task/deps.py", line 53, in run
    final_deps = resolve_packages(packages, self.config)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/deps/resolver.py", line 137, in resolve_packages
    target = final[package].resolved().fetch_metadata(config, renderer)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/deps/base.py", line 85, in fetch_metadata
    self._cached_metadata = self._fetch_metadata(project, renderer)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/deps/git.py", line 102, in _fetch_metadata
    loaded = Project.from_project_root(path, renderer)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/config/project.py", line 642, in from_project_root
    partial = cls.partial_load(project_root, verify_version=verify_version)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/config/project.py", line 609, in partial_load
    return PartialProject.from_project_root(
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/config/project.py", line 455, in from_project_root
    project_dict = _raw_project_from(project_root)
  File "/Users/ipenev/repos/repo3/source/.venv/lib/python3.8/site-packages/dbt/config/project.py", line 153, in _raw_project_from
    raise DbtProjectError(
dbt.exceptions.DbtProjectError: Runtime Error
  no dbt_project.yml found at expected path /var/folders/g7/6hvwgqks4kl69bpl428pdl5h0000gn/T/dbt-downloads-cvlom8wt/c4cd59c6b0d9803e4aa7bb7d61ccf434/dbt_project.yml
```

### Steps To Reproduce
This is our packages file:

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.6
  - package: dbt-labs/spark_utils
    version: 0.2.4
  - git: "https://github.com/databricks/dbt-databricks.git"
    revision: "main"
    warn-unpinned: false
```

`dbt --debug  deps --project-dir=/Users/ipenev/repos/repo3/source/data_ops/dbt --profiles-dir=/Users/ipenev/repos/repo3/source/data_ops/dbt --target=dev`  is the command I ran, although the target is irrelevant imo. The project-dir and profiles-dir just point to the directory where we keep the dbt_project.yml, packages.yml, and profiles.yml files.

### Expected behavior
We'd expect that the package successfully installs so that we can run our dbt models on the databricks adapter. 

### System information
**The output of `dbt --version`:**
```
ipenev@RHV4MQM9CN source % dbt --version
installed version: 0.20.2
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - spark: 0.20.2
```

**The operating system you're using:**
macOS Monterey

**The output of `python --version`:**
```
ipenev@RHV4MQM9CN source % python --version
Python 3.8.14
```

**Comment by ueshin** [comment]
Hi @ivankpenev, thanks for trying `dbt-databricks`.

I'm afraid it's not a right way to install adapters, AFAIK. As `dbt-databricks` is not a package but an adapter as same as `dbt-spark`, we should just run `pip install dbt-databricks`.
We should also modify the profile. See [Set up a Databricks Target](https://docs.getdbt.com/reference/warehouse-profiles/databricks-profile#set-up-a-databricks-target).
There are some behavior differences between `dbt-spark` and `dbt-databricks`. Please also see [Caveats](https://docs.getdbt.com/reference/warehouse-profiles/databricks-profile#caveats).

Btw, `dbt-databricks` only works with `dbt>=1.0.0`. Please try with as latest dbt as possible.

Thanks.

**Comment by ivankpenev** [comment]
Gotcha, I will give these things a try! Thank you
