### ISSUE TITLE
databricks=1.8.0-rc1: 'managed_shallow_clone' is not a valid DatabricksRelationType

### ISSUE THREAD

**Issue by stevenayers-bge** [databricks/dbt-databricks#669]
### Describe the bug
Error when running `dbt compile`:

```bash
$ dbt compile
11:19:00  Running with dbt=1.8.0
11:19:03  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
11:19:03  Registered adapter: databricks=1.8.0-rc1
11:19:03  Unable to do partial parsing because of a version mismatch
11:19:08  Found 64 models, 2 operations, 607 data tests, 35 sources, 1688 macros
11:19:08  
11:25:31  Encountered an error:
'managed_shallow_clone' is not a valid DatabricksRelationType
11:25:31  Traceback (most recent call last):
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/requires.py", line 218, in wrapper
    return func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/requires.py", line 247, in wrapper
    return func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/requires.py", line 294, in wrapper
    return func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/requires.py", line 332, in wrapper
    return func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/cli/main.py", line 342, in compile
    results = task.run()
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/task/runnable.py", line 526, in run
    result = self.execute_with_hooks(selected_uids)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/task/runnable.py", line 486, in execute_with_hooks
    self.before_run(adapter, selected_uids)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/task/runnable.py", line 474, in before_run
    self.populate_adapter_cache(adapter)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/task/runnable.py", line 464, in populate_adapter_cache
    adapter.set_relations_cache(cachable_nodes)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/adapters/base/impl.py", line 523, in set_relations_cache
    self._relations_cache_for_schemas(relation_configs, required_schemas)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/adapters/base/impl.py", line 499, in _relations_cache_for_schemas
    for relation in future.result():
  File "/path/to/home/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/path/to/home/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/path/to/home/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt_common/utils/executor.py", line 13, in connected
    return func(*args, **kwargs)
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/adapters/databricks/impl.py", line 233, in list_relations_without_caching
    return [
  File "/path/to/repo/.venv/lib/python3.10/site-packages/dbt/adapters/databricks/impl.py", line 238, in <listcomp>
    type=self.Relation.get_relation_type(kind),
  File "/path/to/home/.pyenv/versions/3.10.13/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/path/to/home/.pyenv/versions/3.10.13/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'managed_shallow_clone' is not a valid DatabricksRelationType

```

**Comment by Villaz** [comment]
I'm having the same issue using databricks=1.8.1
