### ISSUE TITLE
Error with table type 'managed_shallow_clone' when running codegen

### ISSUE THREAD

**Issue by kalebkemp** [databricks/dbt-databricks#873]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
When running the following command, I get an error about an invalid relation type
```bash
dbt run-operation generate_source --quiet --args '{"schema_name": "my_dev_schema", "database_name": "my_dev_database" }' > models/staging/my_dev_schema/_my_dev_schema__sources.yml
```
I am able to fix the error by adding the following line in the file .venv\Lib\site-packages\dbt\adapters\databricks\relation.py

```python
class DatabricksRelationType(StrEnum):
    Table = "table"
    View = "view"
    CTE = "cte"
    MaterializedView = "materialized_view"
    Foreign = "foreign"
    StreamingTable = "streaming_table"
    ShallowClone = "managed_shallow_clone" ### ADDED THIS LINE
    External = "external"
    Unknown = "unknown"
```

I'm not sure the implications of just adding this, so I didn't want to submit the code myself, but it does fix the issue for me and I haven't seen any other issues caused by this.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Try to run that generate source command on a schema with tables that are managed_shallow_clone table types. These can be created by running the following in databricks on a serverless cluster (in the newest databricks release)

```sql
CREATE or replace table my_dev_catalog.my_database.my_table SHALLOW CLONE my_prod_catalog.my_database.my_table
```

### Expected behavior
A sources.yml file is generated without error

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.
```
18:48:54  Encountered an error while running operation: Database Error
  Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'managed_shallow_clone'
```
### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.8
  - latest:    1.9.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - databricks: 1.8.7 - Update available!
  - spark:      1.8.0 - Update available!
```

**The operating system you're using:**
Windows 11
**The output of `python --version`:**
Python 3.12.4

**Comment by benc-db** [comment]
Are there any debug logs?  Can you share the stack around the error?

**Comment by kalebkemp** [comment]
> Are there any debug logs? Can you share the stack around the error?

```
14:27:38.507979 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020934AE3170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020934DBF950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020934DBEF90>]}


============================== 14:27:38.514980 | 59496169-0253-4b1f-89db-be130e91bbeb ==============================
14:27:38.514980 [info ] [MainThread]: Running with dbt=1.8.8
14:27:38.515979 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\github\\DataOps\\data-lake-dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'C:\\github\\DataOps\\data-lake-dbt\\logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'True', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run-operation generate_source --quiet --args {schema_name: quintiq, database_name: dev_landing }', 'send_anonymous_usage_stats': 'True'}

14:27:38.823275 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
14:27:38.823275 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
14:27:38.824294 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR

14:27:40.465602 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '59496169-0253-4b1f-89db-be130e91bbeb', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002095FCC3230>]}
14:27:40.538185 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '59496169-0253-4b1f-89db-be130e91bbeb', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002095FC33350>]}
14:27:40.539186 [info ] [MainThread]: Registered adapter: databricks=1.8.7
14:27:40.558701 [debug] [MainThread]: checksum: ec53e341a936509427e16df1c646386a84befec52c1957e3f4359fbc36fc93f5, vars: {}, profile: , target: , version: 1.8.8

14:27:41.651130 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 1 files added, 0 files changed.
14:27:41.656160 [debug] [MainThread]: Partial parsing: added file: logan_data_lake://models\staging\quintiqtest\_quintiqtest__sources.yml

14:27:41.951946 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '59496169-0253-4b1f-89db-be130e91bbeb', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002095FC64BF0>]}

14:27:42.677068 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '59496169-0253-4b1f-89db-be130e91bbeb', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020960AD8470>]}
14:27:42.677068 [info ] [MainThread]: Found 1357 models, 1192 sources, 2 exposures, 741 macros
14:27:42.678252 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '59496169-0253-4b1f-89db-be130e91bbeb', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002096016F500>]}
14:27:42.679233 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0s, acquire-count=0, language=None, thread-identifier=(17980, 34076), compute-name=) - Creating connection
14:27:42.679233 [debug] [MainThread]: Acquiring new databricks connection 'macro_generate_source'
14:27:42.680232 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Acquired connection on thread (17980, 34076), using default compute resource
14:27:42.680232 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Checking idleness
14:27:42.681232 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.0010004043579101562s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Retrieving connection
14:27:42.681232 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.0010004043579101562s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Checking idleness
14:27:42.682232 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.002000093460083008s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Retrieving connection
14:27:42.682232 [debug] [MainThread]: Spark adapter: NotImplemented: add_begin_query
14:27:42.683231 [debug] [MainThread]: Spark adapter: NotImplemented: commit
14:27:42.722516 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.04127383232116699s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Checking idleness
14:27:42.723516 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=None, name=macro_generate_source, idle-time=0.043283700942993164s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Retrieving connection
14:27:42.724516 [debug] [MainThread]: Using databricks connection "macro_generate_source"
14:27:42.725514 [debug] [MainThread]: On macro_generate_source: /* {"app": "dbt", "dbt_version": "1.8.8", "dbt_databricks_version": "1.8.7", "databricks_sql_connector_version": "3.1.2", "profile_name": "logan_data_lake", "target_name": "dev", "connection_name": "macro_generate_source"} */


      

        select distinct
            table_schema as `table_schema`,
            table_name as `table_name`,
            
            case table_type
                when 'MANAGED' then 'table'
                when 'BASE TABLE' then 'table'
                when 'MATERIALIZED VIEW' then 'materializedview'
                else lower(table_type)
            end as `table_type`

        from dev_landing.information_schema.tables
        where table_schema ilike 'quintiq'
        and table_name ilike '%'
        and table_name not ilike ''


14:27:42.726514 [debug] [MainThread]: Opening a new connection, currently in state init

14:27:43.213220 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=01efb7fe-6324-103f-bd14-9f95a96cfd6d, name=macro_generate_source, idle-time=0.0s, acquire-count=1, language=None, thread-identifier=(17980, 34076), compute-name=) - Connection created
14:27:43.215220 [debug] [MainThread]: Databricks adapter: Cursor(session-id=01efb7fe-6324-103f-bd14-9f95a96cfd6d, command-id=Unknown) - Created cursor

14:27:44.812487 [debug] [MainThread]: SQL status: OK in 2.090 seconds
14:27:44.826373 [debug] [MainThread]: Databricks adapter: Cursor(session-id=01efb7fe-6324-103f-bd14-9f95a96cfd6d, command-id=01efb7fe-6349-1b44-b9ce-ed4642a91895) - Closing cursor
14:27:44.828888 [debug] [MainThread]: Databricks adapter: Exception while trying to execute query
macro generate_source
: Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'managed_shallow_clone'
14:27:44.830250 [debug] [MainThread]: Databricks adapter: DatabricksDBTConnection(id=2239299944912, session-id=01efb7fe-6324-103f-bd14-9f95a96cfd6d, name=macro_generate_source, idle-time=0.0s, acquire-count=0, language=None, thread-identifier=(17980, 34076), compute-name=) - Released connection
14:27:44.831251 [error] [MainThread]: Encountered an error while running operation: Database Error
  Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'managed_shallow_clone'
14:27:44.841720 [debug] [MainThread]: Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\dataclass_schema.py", line 166, in _deserialize
    return cls(value)
           ^^^^^^^^^^
  File "c:\Users\kkemp\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kkemp\AppData\Local\Programs\Python\Python312\Lib\enum.py", line 1171, in __new__
    raise ve_exc
ValueError: 'managed_shallow_clone' is not a valid DatabricksRelationType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\adapters\databricks\connections.py", line 508, in exception_handler
    yield
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\adapters\base\impl.py", line 1155, in execute_macro
    result = macro_function(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\clients\jinja.py", line 336, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\clients\jinja.py", line 299, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 768, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 42, in macro
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\clients\jinja.py", line 84, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\clients\jinja.py", line 299, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 768, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 131, in macro
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\clients\jinja.py", line 84, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\clients\jinja.py", line 299, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 768, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 42, in macro
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\clients\jinja.py", line 84, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\clients\jinja.py", line 299, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 768, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 28, in macro
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\clients\jinja.py", line 84, in __call__
    return self.call_macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt_common\clients\jinja.py", line 299, in call_macro
    return macro(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 768, in __call__
    return self._invoke(arguments, autoescape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 49, in macro
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\jinja2\runtime.py", line 303, in call
    return __obj(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\context\providers.py", line 104, in create
    return self._relation_type.create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\adapters\base\relation.py", line 342, in create
    return cls.from_dict(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 19, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'managed_shallow_clone'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\task\run_operation.py", line 62, in run
    self._run_unsafe(package_name, macro_name)
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\task\run_operation.py", line 47, in _run_unsafe
    res = adapter.execute_macro(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\adapters\base\impl.py", line 1154, in execute_macro
    with self.connections.exception_handler(f"macro {macro_name}"):
  File "c:\Users\kkemp\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "c:\github\DataOps\data-lake-dbt\.venv\Lib\site-packages\dbt\adapters\databricks\connections.py", line 524, in exception_handler
    raise DbtDatabaseError(str(exc)) from exc
dbt_common.exceptions.base.DbtDatabaseError: Database Error
  Field "type" of type Optional[DatabricksRelationType] in DatabricksRelation has invalid value 'managed_shallow_clone'

14:27:44.850088 [debug] [MainThread]: Command `dbt run-operation` failed at 14:27:44.850088 after 6.69 seconds
14:27:44.850732 [debug] [MainThread]: Connection 'macro_generate_source' was properly closed.
14:27:44.850879 [debug] [MainThread]: On macro_generate_source: ROLLBACK
14:27:44.851408 [debug] [MainThread]: Databricks adapter: NotImplemented: rollback
14:27:44.852051 [debug] [MainThread]: On macro_generate_source: Close
14:27:44.852051 [debug] [MainThread]: Databricks adapter: Connection(session-id=01efb7fe-6324-103f-bd14-9f95a96cfd6d) - Closing connection

14:27:45.053578 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209348BA270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020960AD81D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020960002990>]}
14:27:45.055577 [debug] [MainThread]: Flushing usage events
```

seems like another potential fix could be adding `when 'managed_shallow_clone' then 'table'` to the following:
```
        select distinct
            table_schema as `table_schema`,
            table_name as `table_name`,
            
            case table_type
                when 'MANAGED' then 'table'
                when 'BASE TABLE' then 'table'
                when 'MATERIALIZED VIEW' then 'materializedview'
                else lower(table_type)
            end as `table_type`

        from dev_landing.information_schema.tables
        where table_schema ilike 'quintiq'
        and table_name ilike '%'
        and table_name not ilike ''
```

**Comment by benc-db** [comment]
Thanks!

**Comment by benc-db** [comment]
Ah, this is technically an issue in the codegen plugin, but as you say, we can fix it by adding the type in relation.py

**Comment by kalebkemp** [comment]
> Ah, this is technically an issue in the codegen plugin, but as you say, we can fix it by adding the type in relation.py

Gotcha, I wasn't sure who to open this with. I did open it there first and they referred me here, probably because of my initial suggested solution. Thanks for working on it! Like I mentioned, I was able to work-around so it wasn't a big deal, but I didn't want someone else to encounter the same issue
